globals:
    debug: false
    debugUSB: false
    debugANT: true
    debugBLE: true
    debugWWW: true
    server: 3000

equipments:
    trainerANT: false
    trainerBLE: false
    tacxUSB: true

physics:
    debug: true
    max_grade: 11
    max_speedms: 55
    mass_rider: 89
    mass_bike: 11

tacxUSB:
    debug: true
    vendorid: 0x3561
    productid: 0x1932
    datalog: true
    simulation: false
    datafile: ""
    period: 500
    powercurve: "trainers/power_calc_factors_imagic.txt"
    min_power: 5
    max_power: 800

trainerANT:
    debug: true

trainerBLE:
    debug: true

xport:
    baudrate: 9600
    dataBits: 8
    parity: 'none'
    stopBits: 1
    flowControl: false
    parserLength: 40

xintervals:
    flushNext: 50
    getAdress: 100
    runData: 500
    restart: 1000