DEBUG:
    daumUSB: false
    server: false
    BLE: false
    FC: false
    Trainer: false

globals:
    windspeed_ble: 1
    grade_ble: 1
    crr_ble: 0.0040
    cw_ble: 0.51
    wheel: 2.095
    

server:
    port: 3000

timeouts:
    open: 2000
    start: 2000

simulation:
    maxGrade: 16
    mRider: 72
    mBike: 9
    g: 9.8067
    p: 1.225
    e: 0.97

