globals:
    debug: true
    server: 3000

debug:
    debug: true
    easyUSB: true
    tacxUSB: true
    trainerANT: true
    fitness-control-point: true
    fitness-machine-status: true
    indoor-bike-data: true
    smart-trainer: true
    server: true

physics:
    debug: true
    max_grade: 11
    max_speedms: 55
    height_rider: 1.8
    mass_rider: 89
    mass_bike: 11
    avg_power: 200
    windspeed: 0.0
    crr: 0.0033
    cw: 0.34

tacxUSB:
    vendorid: 0x3561
    productid: 0x1932
    datalog: false
    simulation: false
    datafile: ""
    period: 500
    count: 2
    powercurve: "trainers/power_calc_factors_imagic.txt"
    speed_min: 10
    power_step: 5
    power_max: 800
    rpm: false
    hr: false
    speed: false

sensorANT:
    wheel: 2.199
    period: 1000
