globals:
    debug: false
    debugUSB: false
    debugANT: true
    debugBLE: true
    debugWWW: true
    server: 3000

equipments:
    trainerANT: false
    tacxUSB: true

physics:
    debug: true
    max_grade: 11
    max_speedms: 55
    height_rider: 1.8
    mass_rider: 89
    mass_bike: 11
    avg_power: 200
    windspeed: 0.0
    crr: 0.0033
    cw: 0.34

tacxUSB:
    debug: true
    vendorid: 0x3561
    productid: 0x1932
    datalog: true
    simulation: false
    datafile: ""
    period: 500
    count: 2
    powercurve: "trainers/power_calc_factors_imagic.txt"
    speed_min: 10
    power_step: 5
    power_max: 800
    rpm: false
    hr: false

trainerANT:
    debug: true
